language: clojure
lein: 2.7.1
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - $CMD
env:
  - CMD="lein with-profile 1.7 test-all"
  - CMD="lein with-profile 1.9 test-min"
  - CMD="lein with-profile 1.9-no-spec test-min"
jdk:
  - openjdk7
  - oraclejdk8
